<a href="https://colab.research.google.com/github/rai-shi/Machine-Learning-Gelecegi-Yazanlar/blob/main/multi_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/Advertising.csv")
df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [4]:
df = df.iloc[:,1:]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [10]:
X = df.drop("sales", axis=1)
Y = df[["sales"]] # make it pandas dataframe, [] numpy array [[]] dataframe

In [8]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [11]:
Y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [ ]:
# statsmodels ile model kurmak
# daha fazla bilgi, doğrusal modellerin yapısına uygun bazı sonuçlar

In [13]:
import statsmodels.api as sm

In [15]:
model = sm.OLS(Y,X).fit() # ordinary least square

In [16]:
model.summary() # model output

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Wed, 05 Feb 2025   Prob (F-statistic):                   2.43e-171
Time:                        16:38:41   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

r2 bağımsız değişkenlerin bağımlı değişkeni açıklama yüzdesi, üç değişken ile %98 oranında sales değişkeni açıklanabilmektedir

düzeltilmiş r2, r2 formülasyonu itibari ile veri setine ne kadar değişken eklenirse eklensin artmaya meyilldir. iligli ilgisiz birçok değişkeni modele dahil eder.

r2 artması her zaman açıklanabilirliğe katkı sağlamaz o yüzden düzeltilmiş r2 daha tutarlıdır

f istatistiği modelin anlamlılığına dair istatistiksel test sonucu (0.05 den küçük olmalı ki anlamlı olsun)

alltaki tablo veri setindeki değişkene ait bilgileri içeriyor.
coef beta katsayıları, std err katsayıların standart hatası,
t istatistiği ve p value ile değişkenlerin anlamlılığı, hepsi 0.05 den küçük olduğu için anlamlıdır. h0 anlamlı değildir der.

bir bağımsız değişkenin katsayısı x birim ise diğerlerinin sabit olduğu durumda x katsayılı değişkenin bir birimlik değişimi bağımlı değişkene x birim etki eder. bağımsız değişkenlerin bağımlı değişkene nasıl etki edeceğinin birimidirler.

In [ ]:
# skitlearn ile model kurmak
# sadece katsayılar

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
lm = LinearRegression()

In [22]:
model = lm.fit(X, Y)

In [24]:
print(model.coef_)

[[ 0.04576465  0.18853002 -0.00103749]]


In [25]:
print(model.intercept_)

[2.93888937]


In [26]:
# katsayılar parametre tahmin yöntemleri farklı olmsaından farklılaştı

**model**

In [29]:
print ("sales = %.2f + TV*%.2f + radio*%.2f + newspaper*%.5f" % (model.intercept_, model.coef_[0][0], model.coef_[0][1], model.coef_[0][2]) )

sales = 2.94 + TV*0.05 + radio*0.19 + newspaper*-0.00104


<ipython-input-29-31ce5adc20e4>:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print ("sales = %.2f + TV*%.2f + radio*%.2f + newspaper*%.5f" % (model.intercept_, model.coef_[0][0], model.coef_[0][1], model.coef_[0][2]) )


In [30]:
new_data = [
    [30, 10, 40],
    [5, 25, 80],
    [45, 100, 12],
]

new_data = pd.DataFrame(new_data, columns=["TV", "radio", "newspaper"])
new_data

TV  radio  newspaper
0  30     10         40
1   5     25         80
2  45    100         12

In [31]:
model.predict(new_data)

array([[ 6.15562918],
       [ 7.79796358],
       [23.83885019]])

In [36]:
for i in range(len(new_data)):
  sales = model.intercept_ + new_data.iloc[i,0]*model.coef_[0][0] + new_data.iloc[i,1]*model.coef_[0][1] + new_data.iloc[i,2]*model.coef_[0][2]
  print(sales)

[6.15562918]
[7.79796358]
[23.83885019]


In [37]:
# model performansı

In [40]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [44]:
mse = mean_squared_error(Y, model.predict(X))
mse

2.784126314510936

In [45]:
rmse = np.sqrt(mse)
rmse

1.6685701407225697

In [46]:
# model tuning, model doğrulama

In [49]:
# çoklu doğrusal regresyon modelinde bir hiper parametre yoktur bu durumda burada model doğrulama işlemleri gerçekleşecek
# sınama seti ve k katlı çaprazlama ile yapacağız

In [50]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [51]:
Y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [53]:
# sınama seti, holdout
from sklearn.model_selection import train_test_split

In [54]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=99)

In [55]:
x_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [57]:
X.shape

(200, 3)

In [58]:
x_train.shape

(160, 3)

In [59]:
x_test.shape

(40, 3)

In [60]:
model2 = LinearRegression().fit(x_train, y_train)

In [61]:
# train error
np.sqrt(mean_squared_error(y_train, model2.predict(x_train)))

1.7236824822650754

In [62]:
# test error
np.sqrt(mean_squared_error(y_test, model2.predict(x_test)))

1.4312783138301641

In [67]:
# k-katlı cross validation
from sklearn.model_selection import cross_val_score
errors = cross_val_score(model2, x_train, y_train, cv=10, scoring="neg_mean_squared_error")
errors

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [65]:
# train seti içinden 10 farklı hata elde edildi en son ortalama alındığında train setinin ortalama hatası elde ediliyor

In [69]:
np.mean(-errors) # cv mse

3.3170289742341246

In [70]:
np.sqrt(np.mean(-errors)) # cv rmse

1.8212712522395242

In [ ]:
# veri seti yeteri kadar büyükse train test yapıp trainde cv uygulayıp en son bir de testseti ile test yapılabilir
# eğer küçük bir veri seti ise o halde X Y üzerinden çalışılır